server {
    listen 80;
    server_name orderzz.com www.orderzz.com;

    location / {
        return 301 https://www.orderzz.com$request_uri;
    }

}


server {
    listen 443 ssl default_server;
    server_name orderzz.com;

    ssl_certificate /certs/fullchain.pem;
    ssl_certificate_key /certs/privkey.pem;

    return 301 https://www.orderzz.com$request_uri;

}
    

server {
    listen 443 ssl;
    server_name www.orderzz.com;

    root /var/www;
    index index.html index.htm;

    ssl_certificate /certs/fullchain.pem;
    ssl_certificate_key /certs/privkey.pem;
    
    location / {
        resolver 127.0.0.11;
        try_files $uri /index.html;
    }

}
    
